"""Article 모델에 tags, reference_count, section_count, thumbnail_path 추가

Revision ID: 512f6dbb53f5
Revises: cf295f11de6e
Create Date: 2026-05-26 09:37:03.741544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '512f6dbb53f5'
down_revision: Union[str, Sequence[str], None] = 'cf295f11de6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.JSON(), nullable=False, server_default='[]'))
        batch_op.add_column(sa.Column('reference_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('section_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('thumbnail_path', sa.String(length=500), nullable=False, server_default=''))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('thumbnail_path')
        batch_op.drop_column('section_count')
        batch_op.drop_column('reference_count')
        batch_op.drop_column('tags')

    # ### end Alembic commands ###
