"""Article/PipelineRun 모델 확장

Revision ID: b0f36a26b832
Revises: 512f6dbb53f5
Create Date: 2026-05-26 12:49:41.051453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0f36a26b832'
down_revision: Union[str, Sequence[str], None] = '512f6dbb53f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('published_url', sa.String(length=500), server_default='', nullable=False))
        batch_op.add_column(sa.Column('scheduled_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('extra_meta', sa.JSON(), server_default='{}', nullable=False))

    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('duration_seconds', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('stage_durations', sa.JSON(), server_default='{}', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.drop_column('stage_durations')
        batch_op.drop_column('duration_seconds')
        batch_op.drop_column('retry_count')

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('extra_meta')
        batch_op.drop_column('scheduled_at')
        batch_op.drop_column('published_url')
        batch_op.drop_column('published_at')

    # ### end Alembic commands ###
